#!/usr/bin/env python3

from http import client
import time

def printrow(row):
    r = ''
    for pixel in '%8s' % bin(row)[2:]:
        if pixel == '1':
            r+='X'
        else:
            r+=' '
    print(r)

def main():
    http_c = client.HTTPConnection('localhost', 5000)

    while True:
        http_c.request('GET', '/screendump/0')
        rows = http_c.getresponse().read()

        print('\n\n\n\n\n\n')
        for row in rows:
            printrow(row)

        time.sleep(1)

if __name__ == '__main__':
    main()
