#!/usr/bin/env python3
from http import client
import select
import socket
import struct
import sys

settings = {
    'port': 12345,
    'bind_addr': '0.0.0.0',
    'http_hostname': None,
    'http_port': None,
}

def serve(s):
    s.setblocking(False)
    http_c = client.HTTPConnection(
        settings['http_hostname'],
        settings['http_port'],
    )
    while True:
        http_c.request('GET', '/screencount')
        count = int(http_c.getresponse().read())
        with select.epoll() as poll:
            poll.register(s.fileno(), select.EPOLLIN | select.EPOLLPRI)
            screen_id = 0
            print('Fetch screen dump %d' % screen_id)
            http_c.request('GET', '/screendump/%d' % screen_id)
            r = http_c.getresponse()
            dump = r.read()
            #dump = struct.pack('B', screen_id) + dump

            print('Sending screen dump')
            print(dump)
            s.send(dump)

            poll.poll(1)

            try:
                data = s.recv(1)
                print('Got data' + repr(data))
            except BlockingIOError:
                pass

def main():
    # Access to the web server
    settings['http_hostname'] = sys.argv[1]
    settings['http_port'] = int(sys.argv[2])

    # Server socket
    srvsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srvsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srvsock.bind(('0.0.0.0', 12345))
    srvsock.listen(1)


    while True:
        (s, addr) = srvsock.accept()
        print('Connection accepted')
        try:
            serve(s)
        except:
            s.close()


if __name__ == '__main__':
    main()
