#!/usr/bin/env python3
from http import client
import socket
import sys
import time

settings = {
    'port': 12345,
    'bind_addr': '0.0.0.0',
    'http_hostname': None,
    'http_port': None,
}

def serve(s):
    s.setblocking(False)
    while True:
        print('Sending screen dump')
        try:
            s.send(bytes(9))
        except:
            s.close()
            return
        time.sleep(1)
        # Read from socket
        # Read screen

def main():
    # Access to the web server
    settings['http_hostname'] = sys.argv[1]
    settings['http_port'] = int(sys.argv[2])

    # Server socket
    srvsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srvsock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srvsock.bind(('0.0.0.0', 12345))
    srvsock.listen(1)


    while True:
        (s, addr) = srvsock.accept()
        print('Connection accepted')
        serve(s)


if __name__ == '__main__':
    main()
